### ISSUE TITLE
What about Magento 2.4

### ISSUE THREAD

**Issue by omariskandarone** [mageplaza/magento-2-arabic-language-pack#14]
What is the situation with Magento 2.4? Any chance the extension would work? If not when to expect support for  version 2.4?

**Comment by islamemammokalmat** [comment]
Is it support 2.4 brother @syrianep

**Comment by phamcuongmp** [comment]
@islamemammokalmat The extension now supports Magento 2.4.x perfectly. You all can download and experience its features. Let me know if you have any further queries. I am willing to answer any questions you guys might have.
Thanks for your interest in Mageplaza extensions.
