### ISSUE TITLE
currency symbol is not showing in my custom website view

### ISSUE THREAD

**Issue by halitsavafoglu** [mageplaza/magento-2-arabic-language-pack#3]
In website view "English" the currency symbol is showing everywhere, while it's not at all in "Arabic" view after activating your extention.
check the attachment please.
![untitled](https://user-images.githubusercontent.com/9927930/39056365-2afbcc1a-44bf-11e8-93a9-935dff4b53c1.png)

**Comment by imsamthomas** [comment]
Hi,

AR has not translated completely yet, check and contribute at https://crowdin.com/project/magento-2/ar

**Comment by halitsavafoglu** [comment]
Thanks for the fast response, but I'm asking for Currency Symbol not for a missing translation 😅

**Comment by imsamthomas** [comment]
This guide will help you to configure currency https://www.mageplaza.com/kb/how-to-configure-currency-magento-2.html

Make sure you configure correct store view
