### ISSUE TITLE
How to add more words to translate

### ISSUE THREAD

**Issue by mylooklike** [mageplaza/magento-2-arabic-language-pack#4]
Hi,
I have install using recommended command, In my english version there is some custom words. I want to add Arabic words for those custom english words. I found that pack installed in /vendor/mageplaza/magento-2-arabic-language-pack, when I am adding here new word to translate its not working. Please help me if you can. Thanks a lot.

**Comment by imsamthomas** [comment]
Hi,

You can contribute the language pack at https://crowdin.com/project/magento-2/ar

Regards,
Sam
