### ISSUE TITLE
Missing Strings

### ISSUE THREAD

**Issue by arantawi** [mageplaza/magento-2-arabic-language-pack#8]
Hi,

How can I know what is missing so that I translate it?

Is there any dictionary file or complete list of strings to be translated?

Please guide me.

**Comment by legendhorus** [comment]
Our language packs are based on [Crowdin](https://crowdin.com/project/magento-2) and user contributions.
Since the number of words is too large, we do not have statistics on the number of words that have not been translated.
I am so sorry about that.

**Comment by arantawi** [comment]
OK.. thanks.
